# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 05:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roll_call', '0016_auto_20160816_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcstu',
            name='upperUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
